apiVersion: v1
kind: Service
metadata:
  name: simple-nodejs-app-service
spec:
  selector:
    app: simple-nodejs-app
  ports:
    - protocol: TCP
      port: 3000  # Port exposed by the service
      targetPort: 3000  # Port exposed by the container
  type: LoadBalancer  # Change this to ClusterIP or NodePort if needed
